### PR TITLE
Login and registration ui features

### PR DESCRIPTION
**Pull request by zolwethu**
Web App landing page.

Login and register buttons

### CODE REVIEW

**Comment by zolwethu** [comment]
@Sinawo @BAHLEMAJOLA @NuffSaid-Bore @TshepoMagagula @SphiweJoe Hi team, I've created this branch for the login and registration forms, please check them out and let me know if there is any changes you need, or anything at all in general before merging to the dev branch.

**Review by BAHLEMAJOLA — APPROVED** [review]
Great work 👍

**Review by Sinawo — APPROVED** [review]
@zolwethu This is amazing! I think you may go ahead and merge @NuffSaid-Bore you up!

**Review by NuffSaid-Bore — CHANGES_REQUESTED** [review]
@zolwethu Great work! Can we replace the logo with our actual logo in the landing page.

**Comment by zolwethu** [comment]
> @zolwethu Great work! Can we replace the logo with our actual logo in the landing page.

@NuffSaid-Bore  way ahead of you boss! Please check again and see if there is anything else

**Comment by NuffSaid-Bore** [comment]
> > @zolwethu Great work! Can we replace the logo with our actual logo in the landing page.
> 
> @NuffSaid-Bore way ahead of you boss! Please check again and see if there is anything else

@zolwethu, looks good now. Merge this branch to the dev so we can move on to other things

**Review by NuffSaid-Bore — APPROVED** [review]
@zolwethu You have my approval, thumbs up

**Pull request merged**
